import { execFileSync } from "node:child_process";
import { join } from "node:path";
import { loadConfig } from "../config.js";
import { runEval, type ScenarioSummary } from "../eval/runner.js";
import { SCENARIOS } from "../eval/scenarios.js";
import { reflectAndMutate } from "./reflect.js";

const MIN_MARGIN = 0.5; // never accept a "win" smaller than this, even if variance is ~0.

export interface EvolveOptions {
  generations: number;
}

/**
 * Reflection-driven hill climbing with git worktrees as the checkpoint/rollback
 * mechanism. Each generation:
 *   1. baseline the suite on `main` (re-baselined every gen — the world drifts);
 *   2. branch a worktree, let the reflection operator mutate its skill library;
 *   3. gate on JS syntax, commit, then evaluate the worktree back-to-back (A/B);
 *   4. if the child beats baseline by a variance-sized margin, merge to `main`;
 *      otherwise discard the worktree and branch.
 */
export async function runEvolution(opts: EvolveOptions): Promise<void> {
  const config = loadConfig();
  const mainDir = process.cwd();
  const suite = SCENARIOS.map((s) => s.id);

  for (let gen = 0; gen < opts.generations; gen++) {
    console.log(`\n========== generation ${gen + 1}/${opts.generations} ==========`);

    console.log("[evolve] baselining main…");
    const baseline = await runEval(suite, { cwd: mainDir });
    const worst = pickWorst(baseline);
    if (!worst) {
      console.log("[evolve] no scored scenarios in baseline (all skipped?) — stopping.");
      return;
    }
    const margin = Math.max(MIN_MARGIN, avgStdDev(baseline));

    const branch = `evolve/gen${gen + 1}-${Date.now()}`;
    const wt = join(mainDir, ".evolve", branch.replace(/\//g, "-"));
    git(mainDir, ["worktree", "add", "-b", branch, wt, "HEAD"]);

    let accepted = false;
    try {
      await reflectAndMutate({ config, cwd: wt, worst });

      const changed = changedPaths(wt);
      if (changed.length === 0) {
        console.log("[evolve] reflection made no changes — discarding.");
        continue;
      }
      const badSkill = firstSyntaxError(wt, changed);
      if (badSkill) {
        console.log(`[evolve] syntax gate failed on ${badSkill} — discarding.`);
        continue;
      }

      git(wt, ["add", "-A"]);
      git(wt, ["commit", "-m", `evolve: improve ${worst.scenarioId}\n\nGenerated by the reflection loop.`]);

      console.log("[evolve] evaluating candidate…");
      const child = await runEval(suite, { cwd: wt });
      const childMean = aggregateComparable(child, baseline);
      const baseComparable = aggregateComparable(baseline, child);

      console.log(
        `[evolve] candidate ${round2(childMean)} vs baseline ${round2(baseComparable)} ` +
          `(margin ${round2(margin)})`,
      );

      if (childMean > baseComparable + margin) {
        console.log(`[evolve] ✅ accepted — merging ${branch} into main.`);
        git(mainDir, ["merge", "--no-edit", branch]);
        accepted = true;
      } else {
        console.log("[evolve] ❌ rejected — not an improvement.");
      }
    } catch (err) {
      console.error(`[evolve] generation failed: ${(err as Error).message}`);
    } finally {
      // Remove the worktree first — a branch checked out in a worktree can't be
      // deleted. Keep accepted (merged) branches as history; drop the rest.
      git(mainDir, ["worktree", "remove", "--force", wt]);
      if (!accepted) safeDeleteBranch(mainDir, branch);
    }
  }
}

// --- aggregation ----------------------------------------------------------

/** Mean over only the scenarios scored in BOTH runs — a fair A/B comparison. */
function aggregateComparable(a: ScenarioSummary[], b: ScenarioSummary[]): number {
  const bScored = new Set(b.filter((s) => s.scores.length > 0).map((s) => s.scenarioId));
  const common = a.filter((s) => s.scores.length > 0 && bScored.has(s.scenarioId));
  if (!common.length) return 0;
  return common.reduce((acc, s) => acc + s.mean, 0) / common.length;
}

function avgStdDev(summaries: ScenarioSummary[]): number {
  const scored = summaries.filter((s) => s.scores.length > 0);
  if (!scored.length) return 0;
  return scored.reduce((a, s) => a + s.stdDev, 0) / scored.length;
}

function pickWorst(summaries: ScenarioSummary[]): ScenarioSummary | undefined {
  const scored = summaries.filter((s) => s.scores.length > 0);
  return scored.sort((a, b) => a.mean - b.mean)[0];
}

// --- git / fs helpers -----------------------------------------------------

function git(cwd: string, args: string[]): string {
  return execFileSync("git", args, { cwd, encoding: "utf8" });
}

/** Paths changed in the worktree (porcelain), relative to its root. */
function changedPaths(wt: string): string[] {
  return git(wt, ["status", "--porcelain"])
    .split("\n")
    .map((l) => l.slice(3).trim())
    .filter(Boolean);
}

/** Return the first changed `.js` skill that fails `node --check`, or null. */
function firstSyntaxError(wt: string, changed: string[]): string | null {
  for (const rel of changed) {
    if (!rel.endsWith(".js")) continue;
    try {
      execFileSync("node", ["--check", join(wt, rel)], { stdio: "pipe" });
    } catch {
      return rel;
    }
  }
  return null;
}

function safeDeleteBranch(mainDir: string, branch: string): void {
  try {
    git(mainDir, ["branch", "-D", branch]);
  } catch {
    /* branch may not exist or may be checked out elsewhere */
  }
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
